// examples/Mvc/ClientApp/src/Pages/Users/Dashboard.vue
<script setup>
import { onMounted } from 'vue';
import { Head, Link, router } from '@inertiajs/vue3';
import AppShell from '../../components/AppShell.vue';

const props = defineProps({
  summary: {
    type: Object,
    default: () => ({}),
  },
  recentUsers: {
    type: Array,
    default: null,
  },
  feed: {
    type: Array,
    default: () => [],
  },
});

onMounted(() => {
  if (!props.recentUsers) {
    router.reload({
      only: ['recentUsers'],
      preserveState: true,
      preserveScroll: true,
    });
  }
});
</script>

<template>
  <Head title="Dashboard" />

  <AppShell>
    <section class="page-hero">
      <div class="page-hero__body">
        <p class="eyebrow">Deferred sidebar</p>
        <h1>Users dashboard</h1>
        <p class="page-subtitle">The server ships the dashboard frame first, then Vue asks Inertia for the deferred recent-users sidebar without reloading the page.</p>
      </div>
    </section>

    <section class="stats-grid">
      <article class="stat-card">
        <p class="section-label">Known users</p>
        <strong>{{ summary.total ?? 0 }}</strong>
      </article>

      <article class="stat-card">
        <p class="section-label">Feed strategy</p>
        <strong>Merged activity feed</strong>
      </article>
    </section>

    <section class="card-grid">
      <article data-testid="vue-dashboard-recent-users">
        <header><strong>Recent users</strong></header>

        <ul v-if="recentUsers" class="stack-list">
          <li v-for="user in recentUsers" :key="user.id" class="list-row">
            <strong>{{ user.name }}</strong>
          </li>
        </ul>
        <p v-else class="loading-pill" data-testid="vue-dashboard-loading">Fetching deferred sidebar data…</p>
      </article>

      <article>
        <header><strong>Activity feed</strong></header>
        <ul class="stack-list">
          <li v-for="entry in feed" :key="entry.id" class="list-row">
            <strong>{{ entry.action }}</strong>
            <span class="muted-text">event #{{ entry.id }}</span>
          </li>
        </ul>
      </article>
    </section>

    <div class="button-row">
      <Link href="/users" class="button button--secondary">Back to users</Link>
    </div>
  </AppShell>
</template>

// examples/MinimalApi/ClientApp/src/Pages/Dashboard/Index.jsx
import { Head, Link, router } from '@inertiajs/react';
import { useEffect } from 'react';
import { AppShell } from '../../components/AppShell';

function formatCurrency(value) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(value ?? 0);
}

export default function DashboardIndex({ summary = {}, topUsers = [], monthlyChart, recentActivity = [] }) {
  useEffect(() => {
    if (!monthlyChart) {
      router.reload({
        only: ['monthlyChart'],
        preserveState: true,
        preserveScroll: true,
      });
    }
  }, [monthlyChart]);

  return (
    <>
      <Head title="Dashboard" />
      <AppShell
        title="Operations dashboard"
        subtitle="Eager props render immediately; deferred chart data arrives via a partial reload."
        actions={
          <Link href="/users" role="button" className="secondary">
            Back to users
          </Link>
        }
      >
        {/* KPI row */}
        <div className="grid">
          <article>
            <header><strong>Users</strong></header>
            <p style={{ fontSize: '2.5rem', fontWeight: 700, margin: 0 }}>{summary.users ?? 0}</p>
          </article>
          <article>
            <header><strong>Revenue</strong></header>
            <p style={{ fontSize: '1.75rem', fontWeight: 700, margin: 0 }}>{formatCurrency(summary.revenue)}</p>
          </article>
        </div>

        {/* Chart + top users */}
        <div className="grid">
          <article>
            <header><strong>Active accounts</strong></header>
            <ul>
              {topUsers.map((user) => (
                <li key={user.id}>{user.name}</li>
              ))}
            </ul>
          </article>

          <article data-testid="react-dashboard-chart">
            <header><strong>Monthly chart</strong></header>
            {monthlyChart ? (
              <div>
                {monthlyChart.labels.map((label, i) => (
                  <div key={label} className="chart-row">
                    <span>{label}</span>
                    <strong>{monthlyChart.values[i]}</strong>
                  </div>
                ))}
              </div>
            ) : (
              <p aria-busy="true">Fetching deferred chart data…</p>
            )}
          </article>
        </div>

        {/* Recent activity */}
        <article>
          <header><strong>Latest events</strong></header>
          <div>
            {recentActivity.map((entry) => (
              <div key={entry.id} className="activity-row">
                <strong>{entry.action}</strong>
                <small>{entry.at}</small>
              </div>
            ))}
          </div>
        </article>
      </AppShell>
    </>
  );
}
